### PR TITLE
Pop up window

### PR DESCRIPTION
**Pull request by AdnanOlarmmi**
# Portfolio: details popup window

## Learning objectives

- I used basic JavaScript syntax.
- I used JavaScript to manipulate DOM elements.
- I used JavaScript events.
- I understood how to parse a Figma design to create a UI.
- I Used objects to store and access data.

## Description

For this milestone of my portfolio website, I implemented a popup window that includes the project details on both desktop and mobile devices. In order to do that, I stored the information about my projects in a JavaScript object.

- I implemented the following interactions:
  - When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
  - The popup disappears when the user clicks (or taps) the close (X) button.

- In order to associate each project with the popup window details, I refactored the project section:
  - I used a JavaScript array to store all of the information for all projects.
  - For each project I stored the following pieces of data in a JavaScript object: name, description, featured image, technologies, link to live version, and link to the source.
  - I  updated the main page so that the projects section is created dynamically using the information stored in that JavaScript object
  - After that, I implemented the popup window.
- I implemented popups for both mobile and desktop screen sizes:

<p align="center">
 Pop-up Window mobile preview

 Pop-up Window desktop preview
</p>

### CODE REVIEW

**Review by cynthiainga — COMMENTED** [review]
Hi @AdnanOlarmmi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a contribution from your partner. This is the pair-programming activity which means you need to work with your partner 🙃 😉

Screen Shot 2022-09-08 at 14 00 02

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello @AdnanOlarmmi  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of GitHub Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [x] Please add Project Name in the README file 👍🏻 
- [x] Please add a description of the Project in the README file 👍🏻 
- [x] Please mention the technologies being used in this project in the README file 👍 
- [x] There's a horizontal scroll bar in the Project that doesn't make it Responsive. 
### [HINT]:- Pop-up menu can be implemented using Display property using CSS and JavaScript.

https://user-images.githubusercontent.com/83048208/189232591-bf00bb3f-e4a2-42ea-a9be-f28979e44f62.mov




_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AdnanOlarmmi** [comment]
@zainsadaqat Hi there 🙃 , the project name, do you mean I should change that "**Is-haq Adnan's portfolio**" to **Pop-up window**? 
Screenshot 2022-09-08 232537

**Review by AnselemOdims — APPROVED** [review]
### Hi  @AdnanOlarmmi 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
