### PR TITLE
Add a contact form and finish the mobile version

### PR DESCRIPTION
**Pull request by AdnanOlarmmi**
# Portfolio: add a contact form and finish the mobile version

## Learning objectives

- I Created forms with HTML5 validations.
- I understood the importance of UX.
- I understoodd how to parse a Figma design to create a UI.

## Description

For the third milestone of my portfolio website, I:

- I added a contact form to my portfolio and the portfolio of my coding partner.
- I made sure that I guided my users' experience in a way that helps them fill in the form without frustration.

### General requirements

- I made sure that there are no linter errors.
- I made sure that I used the correct GitHub flow.
- I made sure that I documented my work in a professional way.

### HTML/CSS requirements

- I Followed the list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

### Project requirements

- The section you need to build for this milestone is: 
    - the contact form in the footer:
    <p align="center">
    contact
    </p>
I used template 4

- I Made sure that:
    - Name field accepts up to 30 chars.
    - Email field accepts only emails.
    - The message field accepts up to 500 chars.
    - All fields have placeholder text.
    - All fields have the correct type.
    - A user cannot submit the form if one or more of the fields is empty.
- I Collect data by using the [Formspree service](https://formspree.io/html).
- In order to lay out the elements on the page I used Flexbox.
- I didn't implement any functionality that requires JavaScript.
- I stuck to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A2346).
- Implement the button interactions (enable, hover, etc.).

## Work and submission mode

- I implemented the above requirements in **all repositories** in my pair-programming group. _That means that each group member opened a new pull request in their repo. 😃  🙃

### CODE REVIEW

**Review by prolajumokeoni — APPROVED** [review]
Hi @AdnanOlarmmi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Please always use the same pr for re-reviews, you don't have to create a new pr, this will help reviewers know if all changes requested from previous review has been implemented 👍🏿 
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AdnanOlarmmi** [comment]
@prolajumokeoni  Hi,
Please, does making a new push (git push) automatically update the code in the branch's PR?

I wasn't sure of that, that was why I made a new pull request.

**Comment by prolajumokeoni** [comment]
Yes it does update the branch the pr was created from, you can see all commits made on a pr 🤗

**Comment by AdnanOlarmmi** [comment]
@prolajumokeoni 
Thank you.
I couldn't help but notice that you are a Yoruba lady from Nigeria.

Thanks for making us proud.
Keep winning 🎉 .

Bye for now,
From a junior colleague @AdnanOlarmmi

**Comment by prolajumokeoni** [comment]
Thank you @AdnanOlarmmi, all the best with your future projects 🤗

**Pull request merged**
